'*(*.md|*.yaml|*.yml|*.json|*.css|*.html|*.less)':
    - prettier --write --no-error-on-unmatched-pattern
'*(*.js|*.mjs|*.ts|*.jsx|*.tsx)':
    - prettier --write --no-error-on-unmatched-pattern
    - eslint --fix --no-warn-ignored
